//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctioneerSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuctioneerSharp.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastFullScan.
        /// </summary>
        internal static string ImageLastScanKey {
            get {
                return ResourceManager.GetString("ImageLastScanKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ropes.
        /// </summary>
        internal static string ImageRopesKey {
            get {
                return ResourceManager.GetString("ImageRopesKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scanstats.
        /// </summary>
        internal static string ImageStatsKey {
            get {
                return ResourceManager.GetString("ImageStatsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        internal static string ImageTimeKey {
            get {
                return ResourceManager.GetString("ImageTimeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        internal static string ImageTypeKey {
            get {
                return ResourceManager.GetString("ImageTypeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AucScanData.scans.
        /// </summary>
        internal static string MasterTablePath {
            get {
                return ResourceManager.GetString("MasterTablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currentCount.
        /// </summary>
        internal static string StatCurrentCount {
            get {
                return ResourceManager.GetString("StatCurrentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to earlyDeleteCount.
        /// </summary>
        internal static string StatEarlyDeleteCount {
            get {
                return ResourceManager.GetString("StatEarlyDeleteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elapsed.
        /// </summary>
        internal static string StatElapsed {
            get {
                return ResourceManager.GetString("StatElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ended.
        /// </summary>
        internal static string StatEnded {
            get {
                return ResourceManager.GetString("StatEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to endTime.
        /// </summary>
        internal static string StatEndTime {
            get {
                return ResourceManager.GetString("StatEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expiredDeleteCount.
        /// </summary>
        internal static string StatExpiredDeleteCount {
            get {
                return ResourceManager.GetString("StatExpiredDeleteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missedCount.
        /// </summary>
        internal static string StatMissedCount {
            get {
                return ResourceManager.GetString("StatMissedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newCount.
        /// </summary>
        internal static string StatNewCount {
            get {
                return ResourceManager.GetString("StatNewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oldCount.
        /// </summary>
        internal static string StatOldCount {
            get {
                return ResourceManager.GetString("StatOldCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paused.
        /// </summary>
        internal static string StatPaused {
            get {
                return ResourceManager.GetString("StatPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sameCount.
        /// </summary>
        internal static string StatSameCount {
            get {
                return ResourceManager.GetString("StatSameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to started.
        /// </summary>
        internal static string StatStarted {
            get {
                return ResourceManager.GetString("StatStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to startTime.
        /// </summary>
        internal static string StatStartTime {
            get {
                return ResourceManager.GetString("StatStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updateCount.
        /// </summary>
        internal static string StatUpdateCount {
            get {
                return ResourceManager.GetString("StatUpdateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wasIncomplete.
        /// </summary>
        internal static string StatWasIncomplete {
            get {
                return ResourceManager.GetString("StatWasIncomplete", resourceCulture);
            }
        }
    }
}
